# Generated by Django 5.0.6 on 2024-07-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_winner_listing_winner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
